feat: Customizeable Semantic Colors
catppuccin/daisyui pull request #3
Opened 2024-06-16 01:12 UTC by Skarian

Have really been enjoying using this package in a current project. 

I found it very convenient to be able to select which catppuccin colors were for each semantic category. This will let me serve my client's needs and I imagine such a feature would be very useful for others out there.

Makes some really nice UI.

Have went ahead and implemented it in this PR, let me know what you think of merging.

2024-06-16 06:07 UTC, Liumingxun commented
Thanks for your work! 

In my opinion, certain semantic colors such as `success`, `warning`, or `error` should not be altered by the user; instead, they should follow to the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md), or the theme maybe not have the Catppuccin flavor.

And according to the [Design Philosophy](https://github.com/catppuccin/catppuccin?tab=readme-ov-file#-design-philosophy), the colors of `Monochromatic` may not be suitable for use as the `primary` color. I think the `primary` and `accent` semantic color may use `Accent`(rainbow) color only. As for the `secondary` and `neutral` I have no idea, so just remain the same for now.

Summary:
1. `success`, `warning`, `error`, `info` shouldn't be altered.
2. `primary` and `accent` color should only use the colors within the `AccentName`.
3. `secondary` and `neutral` I have no idea yet, might consider using both `AccentName` and `MonochromaticName` colors.

The above is my thought, feel free to discuss it with me! And last, thanks again for your PR, I am glad to improve this repository with you!

2024-06-17 01:50 UTC, Skarian commented
Added another commit. Overall, really aligned to the feedback, have made the requisite changes with a few small tweaks.

1. Only `MonochromaticName` values assignable to `neutral`: This seems pretty reasonable, I could not think of a scenario where that should be accent colors
2. I left `info` customizable. The reasoning is that since blue is default assigned, if one wants to use `blue` as the primary color they would not be able to use `info` without there being no distinction. This is my current exact use case for instance.

Thanks for being open to the PR. Let me know what you think.

2024-06-17 06:25 UTC, 42Willow commented on .DS_Store
This should be removed, and optionally added to `.gitignore`

2024-06-17 06:26 UTC, 42Willow commented on package-lock.json
This should also be removed, as there is already a pnpm lockfile

2024-06-17 06:27 UTC, 42Willow commented on README.md
> +#### Available Catppuccin Flavors
This should be removed

2024-06-17 06:32 UTC, 42Willow requested changes
Note: this is just my opinion

2024-06-17 06:32 UTC, 42Willow commented on README.md
> +- **Optional fields:** primary, secondary, accent, neutral, success, warning, error, info
```suggestion
- **Optional fields:** primary, secondary, accent, neutral
```

To be honest I'm not sure if secondary or neutral should be able to be customised.

2024-06-17 06:32 UTC, 42Willow commented on src/index.ts
> +      'info': palette.colors[info].hex,
```suggestion
      'info': palette.colors.blue.hex,
```

2024-06-17 06:32 UTC, 42Willow commented on src/index.ts
> +  info: 'blue',
```suggestion
```

2024-06-17 06:32 UTC, 42Willow commented on src/index.ts
> +  info: AccentName
```suggestion
```

2024-06-17 06:32 UTC, 42Willow commented on src/index.ts
> +  const { primary, secondary, accent, neutral, info } = getSemanticColors(customColors)
```suggestion
  const { primary, secondary, accent, neutral } = getSemanticColors(customColors)
```

2024-06-20 11:27 UTC, sgoudham commented
I personally wouldn't modify `info`, `warning`, or `success` as they should be consistent throughout the organisation. 

Info being `teal` is something that's in the code editors section but mostly for historical reasons as I believe catppuccin/nvim uses that. I much prefer `blue` and would like to keep that here. I'll make sure to update the style guide.

I'm not entirely sure how I feel about the argument of no distinction because in the end, we're just mapping variables to colours. Good and accessible design shouldn't rely solely on colour to differentiate visual elements for the user. 🤔

2024-06-24 03:35 UTC, merged

2024-06-24 03:41 UTC, Liumingxun commented
Thanks to all the participants, I made some adjustments and overloaded the API to retain the original usage. This allows users to transition smoothly to the new version. I also kept the custom info color to cover edge cases.

Thanks again everyone.